### ISSUE TITLE
Release libv8 compiled with muslc support in Github Releases

### ISSUE THREAD

**Issue by deepj** [rubyjs/libv8#270]
Hello,
since rubygems can't recognize used glibc or muslc support so it's not possible to release a gem compiled with muslc to rubygems.org. But it's still to possible to release it here in Releases and download it  from here and use it manually, e.g. this way:

```
gem list | grep libv8 || curl -O https://github.com/cowboyd/libv8/releases/download/v6.7.288.46.1/libv8-6.7.288.46.1-x86_64-linux-muslc.gem && gem install libv8-6.7.288.46.1-x86_64-linux-muslc.gem && rm libv8-6.7.288.46.1-x86_64-linux-muslc.gem
```

It's not easy to set and compile `libv8` gem on Alpine Linux. This would help the folks who use Alpine Linux based Docker images. Yes, this is a workaround, but it's some quite easy solution for some of us.

**Comment by volkanunsal** [comment]
This would be great to have. I've been struggling to install libv8 on Alpine for a few days now.

**Comment by ignisf** [comment]
Hello,

Sorry it took a while to get back to you, but while this might work as a workaround for one major issue to getting libv8 on Alpine, the current blocker is https://github.com/cowboyd/libv8/issues/259. I'd gladly publish a binary linked against musl if I could build one at all...

**Comment by deepj** [comment]
@ignisf yeah, it's just a workaround. But I haven't noticed any issue in rubygems/bundler to reflect this issue (gem's muslc support). Maybe worth to create and start a discussion on this topic? I just don't know how to describe the problem well, so I would leave it on someone more knowledgeable/

**Comment by lloeki** [comment]
Hey @ignisf, we ([Sqreen](GitHub.com/sqreen)) maintain and push [libv8-alpine](https://rubygems.org/gems/libv8-alpine) and [libv8-solaris](https://rubygems.org/gems/libv8-solaris) gems, which we built by fetching source outside of the target platforms, then building `libv8_monolith.a` (with some build system patches). It's hackish, and currently stuck at 6.8.

To achieve a sustainable solution, we're tackling this together with upstream, and currently aiming at having `libv8_monolith.a` automatically built from NodeJS's v8, and published upstream for all NodeJS supported platforms (which include Alpine and SmartOS, thus Solaris), starting with libv8 7.4. IIUC this strategy would sidestep #259 entirely as you'd be able to fetch the binaries and use them right away for packaging as a gem.

Does that sound interesting to you?

**Comment by nightpool** [comment]
@lloeki This does sound interesting! Can we create a new tracking issue for this? What's the next step to push this forward on Node's side? Are there any differences between Node's build configuration and ours that we'd have to sort out? Would we run into any incompatibilities with those who wanted to use their own version of v8?

**Comment by lloeki** [comment]
> Can we create a new tracking issue for this? 

I forgot how many issues might be tied to this. Let me create a new issue on this repo to track that overall.

**Comment by lloeki** [comment]
Opened #304 as suggested!

**Comment by lloeki** [comment]
Closing as ruby gems now allows that, plus this issue is completely sidestepped in libv8-node, which does have linux(-gnu) and linux-musl builds.
