### ISSUE TITLE
Reintroduce using system v8 (for Alpine Linux support)

### ISSUE THREAD

**Issue by volkanunsal** [rubyjs/libv8#271]
I'm trying to install libv8 on Alpine. As has been noted here, libv8 build doesn't support Alpine's `muslc` library. So I thought I could use the system library with `--with-system-v8`, but saw that it had been removed in an earlier version. Is there an alternative? What is the best way to install libv8 on Alpine?

**Comment by DanielRedOak** [comment]
We're interested in this as well. You could install the libv8 package via apk and get things into system ruby, but we're doing things via bundler, Gemfiles, and Gemfile.lock so this really isn't viable.

**Comment by ignisf** [comment]
Hello,

Could you point me to a packaged V8 for Alpine? I would like to see how they managed to build the package and explore ways to use it.

I have been thinking about reintroducing linking against a shared library for of V8, however I want to do it correctly this time by verifying version compatibility as well.

**Comment by ciroque** [comment]
Is there any update on this? It has become a huge problem for us...

**Comment by SoreGums** [comment]
so how do we get bundler to see libv8-alpine as libv8?

bundle complains libv8 is not installed...

**Comment by Taiki-San** [comment]
They're different packages, a the Gemfile need to detect when it's running on Alpine and gem `libv8-alpine` instead of `libv8`. The requesting gem also need to aware of the changes in names.
The fix would be to integrate those in the main libv8 package, but I don't know how it's done in other Ruby gems.

**Comment by alyssais** [comment]
This would be useful for us in Nixpkgs as well.

**Comment by lloeki** [comment]
Made a comment here regarding musl support and a possible partially upstream solution: https://github.com/rubyjs/libv8/issues/270#issuecomment-573063347

**Comment by lloeki** [comment]
Closing as musl is supported by libv8-node.
