### ISSUE TITLE
Move `libv8`, `therubyracer`, `therubyrhino` to a `rubyjs` organization

### ISSUE THREAD

**Issue by cowboyd** [rubyjs/libv8#284]
The time has long since passed that these should be on my own personal account. Other folks are maintaining this software and developing the tools and community, and I'm just a drag on it.

I'd like to propose creating a `rubyjs` org to take the usage of JavaScript in Ruby forward, probably with @ignisf and @SamSaffron as the admins.

**Comment by SamSaffron** [comment]
I love this idea and am happy to put mini_racer under that umbrella org as well! 

Happy to leave you @cowboyd  with commit rights on the whole org if you would still like to participate in some form.

@ignisf  clearly gets commit rights. I do feel like it would be nice to have 1 more committer though in case both me and @ignisf  are out for a bit.

**Comment by cowboyd** [comment]
Sounds good, what shall we call it?

**Comment by SamSaffron** [comment]
I like rubyjs if it is available somehow.

**Comment by cowboyd** [comment]
It looks like it's hasn't had any activity for the last five years. Maybe @hasclass or @PikachuEXE would be willing to donate it?

**Comment by hasclass** [comment]
@cowboyd it's been inactive and i don't know of anyone relying on it, so I'd be happy to donate the rubyjs organisation and the rubyjs.org domain. Sent you an email.

**Comment by cowboyd** [comment]
Thanks to gracious donation from @hasclass, I'm closing this issue from the new home of `libv8`, the [rubyjs](https://github.com/rubyjs/libv8/issues/284) org!

He's also volunteered to donate the rubjs.org if anyone thinks there should be a website for it. Also, looks like we'll need some kind of logo to replace the space invader icon.

**Comment by SamSaffron** [comment]
@cowboyd can you grant me admin on rubyjs, I will then move mini_racer there :confetti_ball:

**Comment by ignisf** [comment]
@SamSaffron you already have a pending invitation

**Comment by SamSaffron** [comment]
cool ... mini racer is now moved !!! :)
