### ISSUE TITLE
ppc64le support

### ISSUE THREAD

**Issue by madscientist159** [rubyjs/libv8#285]
Stock libv8 has native support for ppc64le, but the default Gem install process tries to pull in a bunch of x86_64 tooling binaries from Google.

There should be a ppc64le build of the libv8 gem for Linux, given ppc64le is the only open ISA system  with enough horsepower to run Ruby.

**Comment by runlevel5** [comment]
@madscientist159 the `depot_tools` by Chromium Dev team does not offer ppc64le binaries. In theory it is possible to substitute these tools with custom-built but there is no guarantee that it would perform exactly like it was meant to.

**Comment by runlevel5** [comment]
@madscientist159 I managed to get the libv8 v8.1.307.20 built under docker, if you are interested in how, please check out https://github.com/runlevel5/v8-ppc64le

Btw, I also manage build new libv8 gem https://github.com/runlevel5/v8-ppc64le/blob/master/libv8-8.1.307.20-powerpc64le-linux.gem if you need it.

**Comment by lloeki** [comment]
I'm interested in people trying out [libv8-node](https://rubygems.org/gems/libv8-node). No binaries yet but the `ruby` platform gem should build.

**Comment by runlevel5** [comment]
@lloeki yes I could help. Do you have a list of tests that you want me to go through?

**Comment by lloeki** [comment]
@runlevel5 let's track this testing over at https://github.com/sqreen/ruby-libv8-node/issues/11

**Comment by runlevel5** [comment]
@madscientist159 FYI I can confirm the ruby-libv8-node works perfectly. Shall we consider adopting discourse again?

**Comment by lloeki** [comment]
Closing as libv8-node is a much better place to achieve that, as it is extremely non-trivial to sidestep depot_tools in any other way.
