### ISSUE TITLE
Binary builds for darwin20 / macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by lloeki** [rubyjs/libv8#305]
There is no binary gem published (yet) for 7.3.492.27.1 and 8.4.255.0. I failed to produce one (again because of depot tools acting up).

Not to be outdone, I produced this terrible hack to work around it.

Use as follows:

```
./gem-install-libv8-darwin-20.sh 7.3.492.27.1
./gem-install-libv8-darwin-20.sh 8.4.255.0
./gem-install-libv8-darwin-20.sh        # defaults to 8.4.255.0
```

```bash
#!/bin/bash
# filename: gem-install-libv8-darwin-20.sh

set -e
set -u
set -o pipefail

libv8_version="${1:-"8.4.255.0"}"
from='19'
to='20'

gem_home="$(ruby -e 'puts Gem.dir')"
ruby_platform="$(ruby -e 'puts Gem.platforms.select { |p| Gem::Platform === p && p.os =~ /darwin/ }')"
ruby_platform_prefix="${ruby_platform%-*}"

# case "${ruby_platform}" in
#     *universal*)
#         ruby_platform_prefix="x86_64-darwin"
#         ;;
# esac

ruby_platform_from="${ruby_platform_prefix}-${from}"
ruby_platform_to="${ruby_platform_prefix}-${to}"

echo " *** detecting"

echo "${gem_home}"
echo "${ruby_platform}"
echo "${ruby_platform_prefix}"

echo "libv8 ${libv8_version}: ${ruby_platform_from} => ${ruby_platform_to}"

echo " *** downloading"

test -f "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" \
    || curl --fail --output "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" "https://rubygems.org/downloads/libv8-${libv8_version}-${ruby_platform_from}.gem" \
    || curl --fail --output "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem" "https://rubygems.org/downloads/libv8-${libv8_version}-${ruby_platform_prefix}${from}.gem"

echo " *** cleaning"

rm -rfv "${gem_home}/specifications/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gemspec"
rm -rfv "${gem_home}/doc/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
rm -rfv "${gem_home}/gems/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
rm -rfv "${gem_home}/cache/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gem"

echo " *** installing"

gem install "/tmp/libv8-${libv8_version}-${ruby_platform_from}.gem"

echo " *** patching"

mv -v "${gem_home}/specifications/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gemspec"
mv -v "${gem_home}/doc/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
mv -v "${gem_home}/gems/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}
mv -v "${gem_home}/cache/libv8-${libv8_version}-"{"${ruby_platform_from}","${ruby_platform_to}"}".gem"

sed -i~ \
    -e "s/${ruby_platform_prefix}-${from}/${ruby_platform_to}/" \
    -e "s/${ruby_platform_prefix}${from}/${ruby_platform_to}/" \
    "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec"
rm "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec~"

echo " *** result"

find "${gem_home}"/*/"libv8-${libv8_version}-${ruby_platform_to}"
grep --text "${ruby_platform_to}" "${gem_home}/specifications/libv8-${libv8_version}-${ruby_platform_to}.gemspec"
```

**Comment by dlackty** [comment]
Confirmed this works on my laptop. Thank you!

**Comment by lloeki** [comment]
This is a gross hack though, and I have encountered a couple of segfaults (still not sure why, just don’t expect this to be 100% stable) but at least it allows the ball to continue rolling.

**Comment by arianf** [comment]
How has this not been fixed yet

**Comment by SamSaffron** [comment]
will the node based builds work? also ... there is the giant arm question.

**Comment by lloeki** [comment]
I pushed libv8-node darwin20 builds just yesterday. GitHub Actions secretly has a `macos-11.0` CI target but it silently fell back to `macos-10.15` last time I checked, so I built it locally.

https://rubygems.org/gems/libv8-node/versions/14.14.0.0.beta2-x86_64-darwin-20

Tested and working against sq_mini_racer 0.3.1.

In the future both the gems and intermediate V8 artifact static libs + headers will be available in each run's artifacts:

https://github.com/sqreen/ruby-libv8-node/actions/runs/349889868

I'm going to add arm7hf-linux and aarch64-linux at some point, it should be fairly easy with either `docker buildx` or manual qemu+binfmt trickery I did before. As for aarch64-darwin-20, well, I'll need some hardware (maybe I can figure out how to cross-compile but in any case I would be unsure how to test).

**Comment by ldanielw1** [comment]
Does this mean that `gem install libv8` may be fixed soon on Big Sur machines, then? is there potential for an ETA on this issue?

**Comment by SamSaffron** [comment]
@lloeki let me know what gems I should push to rubygems once you have this ready.

**Comment by lloeki** [comment]
@SamSaffron You would not be able to push the libv8-node gems as is, as they're not a drop-in replacement: I wanted these to be usable in parallel of this libv8 gem, so I namespaced it as `Libv8::Node`. Although very close, I consider it a bit too early yet to make the switch.

But what you can do right away is take the current libv8 8.4.255.0 darwin19 gem and transform it into a darwin20 gem (basically what the above hack does) by replacing all references from one into the other, including the paths and serialised gemspec. This works because Big Sur is binary backwards compatible with Catalina.

FYI the segfaults I encountered were -entirely- unrelated to the hack.

**Comment by lloeki** [comment]
Ok, someone try these:

https://www.dropbox.com/s/8qt3o6bvx0npst0/libv8-8.4.255.0-universal-darwin-20.gem?dl=0
https://www.dropbox.com/s/wuwuqhaqcate8k5/libv8-8.4.255.0-x86_64-darwin-20.gem?dl=0

**Comment by lloeki** [comment]
And here are 7.3.492.27.1 for darwin20:

https://www.dropbox.com/s/jtjf75h3qpd9qvd/libv8-7.3.492.27.1-universal-darwin-20.gem?dl=0
https://www.dropbox.com/s/nx9brd2k797t2bx/libv8-7.3.492.27.1-x86_64-darwin-20.gem?dl=0

**Comment by pmusaraj** [comment]
Is the libv8-8.4.255.0-universal-darwin-20.gem binary supposed to work both with and without Rosetta? I tried it using mini_racer, and it worked when Terminal runs with Rosetta, but it fails without it. 

Without Rosetta, it gives this error: 

```
dlopen(/Library/Ruby/Gems/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.bundle, 0x0009): 
missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.bundle - /Library/Ruby/Gems/2.6.0/gems/mini_racer-0.3.1/lib/mini_racer_extension.bundle (LoadError)
```

(Tried this on the macOS-provided Ruby.)

**Comment by lloeki** [comment]
No, it's Intel only. I suppose it could work with Rosetta but I'm unable to test that, lacking the hardware.

**Comment by pmusaraj** [comment]
Thanks, it does work via Rosetta.

**Comment by causztic** [comment]
> And here are 7.3.492.27.1 for darwin20:
> 
> https://www.dropbox.com/s/jtjf75h3qpd9qvd/libv8-7.3.492.27.1-universal-darwin-20.gem?dl=0
> https://www.dropbox.com/s/nx9brd2k797t2bx/libv8-7.3.492.27.1-x86_64-darwin-20.gem?dl=0

I can confirm x86_64 worked for me on Big Sur with rvm

**Comment by SamSaffron** [comment]
Gems are now pushed to rubygems!

**Comment by lloeki** [comment]
Closing this one. I will tracking Apple M1 specific progress over here: https://github.com/rubyjs/libv8/issues/309
