### ISSUE TITLE
register rubyjs.org ?

### ISSUE THREAD

**Issue by cowboyd** [rubyjs/libv8#306]
The original owner of the `rubyjs` github org (@hasclass), also has the `https://rubyjs.org` domain name registered and has offered to donate it to the project. While I don't have the time or the sponsorship to pursue it, others here might. If anybody, or anybody's company is willing to shoulder the cost of registration which is quite minimal, it could be a nice home for a website.

If not, it will lapse in a year's time.

**Comment by lloeki** [comment]
Hey @cowboyd, we discussed this at Sqreen and we're open to discuss sponsoring this.

**Comment by cowboyd** [comment]
@lloeki Awesome!!! @SamSaffron @ignisf what do you all think would be the best way to structure the registration of this (and other shared project resources?

**Comment by SamSaffron** [comment]
This is tricky, can there be an org account on namecheap? then me, you and @ignisf  can all have access to the domain so there is no chance it gets lost if one of us vanishes. 

As to paying for the domain, no problem at all Discourse can pay for this no drama at all. Bigger question is who can make a nice website for this thing? What are we going to put on it?

**Comment by cowboyd** [comment]
I don't know if namecheap does, but we could always transfer it over to dnsimple which has support for orgs. I'd imagine just keeping it for the simplest of placeholders until the need for a website arises.

**Comment by SamSaffron** [comment]
Dnsimple works for me, if you get the account sorted and invite me, I can
sort the bill up and at least setup a redirect to github on the domain

**Comment by cowboyd** [comment]
@SamSaffron invite sent!

**Comment by SamSaffron** [comment]
cool I am in, let me know what to do here, I can sort payment out.

**Comment by cowboyd** [comment]
@SamSaffron If you can give me an email that I can make the admin account (it can't be yours or mine), then you can take the keys with it from there.

**Comment by SamSaffron** [comment]
does sam <at> discourse.org work ?
